/**
 * HelloAGENTS carrier plugin for DeepSeek Harness.
 *
 * Injects the DSH-adapted HelloAGENTS workflow protocol (bootstrap.md) as a
 * system-prompt section, so the model receives the HelloAGENTS routing rules,
 * output format, safety constraints, and sub-agent orchestration protocol in
 * every turn.
 *
 * Generated by `helloagents install dsh`; refresh with `helloagents update`.
 * The row `name: './plugins/helloagents-carrier.mjs'` resolves relative to the
 * preset directory, so the preset stays self-contained and copyable.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export const name = "helloagents-carrier";

export const inject = ["systemPrompt"];

export function apply(ctx) {
  const bootstrapPath = fileURLToPath(
    new URL("../bootstrap.md", import.meta.url),
  );
  const text = readFileSync(bootstrapPath, "utf8");

  ctx.effect(
    () =>
      ctx.systemPrompt.section({
        name: "helloagents:workflow",
        order: 10,
        text,
      }),
    "helloagents-carrier.section()",
  );
}